# encoding: utf-8

#first user
u = User.new(:password => "123456", :password_confirmation => "123456", :email => "admin@apileipzig.de", :name => "Api Admin", :telefon => "0341/1234567", :admin => true, :active => true, :single_access_token => "a")
u.save!

#branches

Branch.create(:name => 'Cluster Medien & Kreativwirtschaft', :internal_type => 'cluster')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_type => 'sub_market', :name => 'Software/Games-Industrie', :internal_key => 'SG')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_type => 'sub_market', :name => 'Buchmarkt', :internal_key => 'BM')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_type => 'sub_market', :name => 'Pressemarkt', :internal_key => 'PM')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_type => 'sub_market', :name => 'Rundfunkwirtschaft', :internal_key => 'RW')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_type => 'sub_market', :name => 'Filmwirtschaft', :internal_key => 'FW')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_type => 'sub_market', :name => 'Markt für darstellende Künste', :internal_key => 'DK')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_type => 'sub_market', :name => 'Kunstmarkt', :internal_key => 'KM')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_type => 'sub_market', :name => 'Musikwirtschaft', :internal_key => 'MW')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_type => 'sub_market', :name => 'Werbemarkt', :internal_key => 'WM')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_type => 'sub_market', :name => 'Designwirtschaft', :internal_key => 'DW')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_type => 'sub_market', :name => 'Architekturmarkt', :internal_key => 'AM')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_key => 'A', :name => 'Druck- und Verlagswesen', :internal_type => 'branch')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_key => 'B', :name => 'Hörfunk, Film, Fernsehen und Video', :internal_type => 'branch')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_key => 'C', :name => 'Informationstechnik, Neue Medien', :internal_type => 'branch')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_key => 'D', :name => 'Werbung, Marketing, Presse- und Öffentlichkeitsarbeit', :internal_type => 'branch')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_key => 'E', :name => 'Weitere Mediendienstleistungen', :internal_type => 'branch')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_key => 'F', :name => 'Medienrelevante Institutionen, Kultureinrichtungen', :internal_type => 'branch')
Branch.create(:parent_id => Branch.find_by_name('Druck- und Verlagswesen').id, :internal_key => 'A1', :name => 'Druckerei', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Druck- und Verlagswesen').id, :internal_key => 'A2', :name => 'Verlag', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Druck- und Verlagswesen').id, :internal_key => 'A3', :name => 'Buchbinderei', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Druck- und Verlagswesen').id, :internal_key => 'A4', :name => 'Reproanstalt, Kopierservice, Setzerei', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Druck- und Verlagswesen').id, :internal_key => 'A5', :name => 'Vertrieb von Druckerzeugnissen', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Druck- und Verlagswesen').id, :internal_key => 'A6', :name => 'Weitere Dienstleistungen', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Hörfunk, Film, Fernsehen und Video').id, :internal_key => 'B1', :name => 'Rundfunkanstalt (öffentlich-rechtlich)', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Hörfunk, Film, Fernsehen und Video').id, :internal_key => 'B2', :name => 'Fernsehsender/Hörfunksender (privat)', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Hörfunk, Film, Fernsehen und Video').id, :internal_key => 'B3', :name => 'Produktionsunternehmen (Hörfunk, Film, Fernsehen, Video)', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Hörfunk, Film, Fernsehen und Video').id, :internal_key => 'B4', :name => 'Verleih und Vertrieb von audio und audiovisuellen Produktionen', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Hörfunk, Film, Fernsehen und Video').id, :internal_key => 'B5', :name => 'Vertrieb von rundfunk- oder filmtechnischen Geräten', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Hörfunk, Film, Fernsehen und Video').id, :internal_key => 'B6', :name => 'Vermietung von Geräten, Einrichtungen, Räumen und Personal', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Hörfunk, Film, Fernsehen und Video').id, :internal_key => 'B7', :name => 'freiberuflich tätig', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Hörfunk, Film, Fernsehen und Video').id, :internal_key => 'B8', :name => 'Weitere Dienstleistungen', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Informationstechnik, Neue Medien').id, :internal_key => 'C1', :name => 'Hardware und Hardwaresysteme', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Informationstechnik, Neue Medien').id, :internal_key => 'C2', :name => 'Netzanbieter (Carrier)', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Informationstechnik, Neue Medien').id, :internal_key => 'C3', :name => 'IT-Netzwerke (Konzeption, Aufbau, Wartung)', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Informationstechnik, Neue Medien').id, :internal_key => 'C4', :name => 'Softwareentwicklung, -vertrieb und Installation (inkl. Datenbanken)', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Informationstechnik, Neue Medien').id, :internal_key => 'C5', :name => 'Multimedia, Online- und audiovisuelle Medien', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Informationstechnik, Neue Medien').id, :internal_key => 'C6', :name => 'Internetpräsentationen und e-Commerce-Lösungen', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Informationstechnik, Neue Medien').id, :internal_key => 'C7', :name => 'Datenerfassung und -bearbeitung', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Informationstechnik, Neue Medien').id, :internal_key => 'C8', :name => 'Telekommunikation', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Informationstechnik, Neue Medien').id, :internal_key => 'C9', :name => 'Weitere Dienstleistungen', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Werbung, Marketing, Presse- und Öffentlichkeitsarbeit').id, :internal_key => 'D1', :name => 'Marketing- und Werbeagentur', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Werbung, Marketing, Presse- und Öffentlichkeitsarbeit').id, :internal_key => 'D2', :name => 'Presse- und Öffentlichkeitsarbeit', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Werbung, Marketing, Presse- und Öffentlichkeitsarbeit').id, :internal_key => 'D3', :name => 'Markt- und Meinungsforschung', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Werbung, Marketing, Presse- und Öffentlichkeitsarbeit').id, :internal_key => 'D4', :name => 'Grafik-, Design- und Fotostudio', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Werbung, Marketing, Presse- und Öffentlichkeitsarbeit').id, :internal_key => 'D5', :name => 'Dienstleister, Zulieferer', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Werbung, Marketing, Presse- und Öffentlichkeitsarbeit').id, :internal_key => 'D6', :name => 'freiberuflich tätig', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Weitere Mediendienstleistungen').id, :internal_key => 'E1', :name => 'Agentur, Archiv', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Weitere Mediendienstleistungen').id, :internal_key => 'E2', :name => 'Beratung und Service', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Weitere Mediendienstleistungen').id, :internal_key => 'E3', :name => 'Call Center, Help Desk', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Weitere Mediendienstleistungen').id, :internal_key => 'E4', :name => 'freiberuflich tätig', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Weitere Mediendienstleistungen').id, :internal_key => 'E5', :name => 'Schulungen, Fort- und Weiterbildung', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Weitere Mediendienstleistungen').id, :internal_key => 'E6', :name => 'Weitere Mediendienstleistungen', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Medienrelevante Institutionen, Kultureinrichtungen').id, :internal_key => 'F1', :name => 'Institution/Verwaltung', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Medienrelevante Institutionen, Kultureinrichtungen').id, :internal_key => 'F2', :name => 'Kultureinrichtung (Theater, Oper, Gewandhaus, Varieté, ...)', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Medienrelevante Institutionen, Kultureinrichtungen').id, :internal_key => 'F3', :name => 'Verband', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Medienrelevante Institutionen, Kultureinrichtungen').id, :internal_key => 'F4', :name => 'Verein', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Medienrelevante Institutionen, Kultureinrichtungen').id, :internal_key => 'F5', :name => 'Bibliothek', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Medienrelevante Institutionen, Kultureinrichtungen').id, :internal_key => 'F6', :name => 'Hoch- und Fachschule', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Medienrelevante Institutionen, Kultureinrichtungen').id, :internal_key => 'F7', :name => 'Weitere Institutionen und Einrichtungen', :internal_type => 'sub_branch')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_type => 'mkw_branch', :name => 'Informations- und Kommunikationstechnologie', :internal_key => '10')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_type => 'mkw_branch', :name => 'Zeitungen und Zeitschriften, Druck- und Verlagsgewerbe', :internal_key => '20')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_type => 'mkw_branch', :name => 'Rundfunk und Film', :internal_key => '30')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_type => 'mkw_branch', :name => 'Künste und Musik', :internal_key => '40')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_type => 'mkw_branch', :name => 'Werbung/Marketing, Öffentlichkeitsarbeit, Messe- und Ausstellungswesen', :internal_key => '50')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_type => 'mkw_branch', :name => 'Architekturmarkt', :internal_key => '60')
Branch.create(:parent_id => Branch.find_by_name('Cluster Medien & Kreativwirtschaft').id, :internal_type => 'mkw_branch', :name => 'Weitere Medien- und kulturelle Dienstleistungen', :internal_key => '70')
